### 수치미분 예제

In [10]:
#수치미분 리뷰
import numpy as np

def numerical_derivative(f, x): #f는 다변수함수, x는 하나이상의 입력변수 모두 ex(x,y)
    delta_x = 1e-4 
    grad = np.zeros_like(x) #grad변수는 수치미분값을 저장할것임 
    
    it = np.nditer(x, flags = ['multi_index'], op_flags = ['readwrite'])
    #it는 넘파이의 모든 요소를 가리키는 iterator이다
    
    while not it.finished: #변수개수만큼 반복
        idx = it.multi_index
        
        tmp_val = x[idx]   #numpy타입은 mutable이므로 원본값 보관
        x[idx] = float(tmp_val) + delta_x   #히나의 변수에 대한 수치미분 계산
        fx1 = f(x)
        
        x[idx] = tm_val - delta_x
        fx2 = f(x)
        grad[idx] = (fx1-fx2) / (2*delta_x) #편미분결과값 grad에 저장
        
        x[idx] = tmp_val  #x에 원본값 전달
        it.iternext()
        
    return grad #결과값 리턴

In [11]:
#수치미분예제 1 f(x) = x^2, f'(3, 0)
def func1(input_obj): #벡터나 행렬을 인수로함
    x = input_obj[0]
    return x**2

In [12]:

import numpy as np

def numerical_derivative(f, x): #f는 다변수함수, x는 하나이상의 입력변수 모두 ex(x,y)
    delta_x = 1e-4 
    grad = np.zeros_like(x) #grad변수는 수치미분값을 저장할것임 
    print("debug 1. inital input variable =", x)
    print("debug 2. inital grad =", grad)
    print("============================================")
    it = np.nditer(x, flags = ['multi_index'], op_flags = ['readwrite'])
    #it는 넘파이의 모든 요소를 가리키는 iterator이다
    
    while not it.finished: #변수개수만큼 반복
        idx = it.multi_index
        
        print("debug 3. idx =", idx, ", x[idx]= ", x[idx])
        
        tmp_val = x[idx]   #numpy타입은 mutable이므로 원본값 보관
        x[idx] = float(tmp_val) + delta_x   #히나의 변수에 대한 수치미분 계산
        fx1 = f(x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        grad[idx] = (fx1-fx2) / (2*delta_x) #편미분결과값 grad에 저장
        
        print("debug 4. grad[idx]", grad[idx])
        print("debug 5. grad = ", grad)
        print("============================================")
        
        x[idx] = tmp_val  #x에 원본값 전달
        it.iternext()
        
    return grad #결과값 리턴

In [9]:
#x = 3.0에서의 편미분값
numerical_derivative( func1, np.array([3.0]))

debug 1. inital input variable = [3.]
debug 2. inital grad = [0.]
debug 3. idx = (0,) , x[idx]=  3.0
debug 4. grad[idx] 6.000000000012662
debug 5. grad =  [6.]


array([6.])

In [15]:
#예제2 f(x,y) = 2x+3xy+y^3, f'(1.0, 2.0)
def func1(input_obj):
    x = input_obj[0]
    y = input_obj[1]
    return (2*x+3*x*y+np.power(y,3))

In [16]:
#(x,y) = (1.0,2.0) 에서의 편미분 값
input = np.array([1.0,2.0])
numerical_derivative(func1, input)

debug 1. inital input variable = [1. 2.]
debug 2. inital grad = [0. 0.]
debug 3. idx = (0,) , x[idx]=  1.0
debug 4. grad[idx] 7.999999999990237
debug 5. grad =  [8. 0.]
debug 3. idx = (1,) , x[idx]=  2.0
debug 4. grad[idx] 15.000000010019221
debug 5. grad =  [ 8.         15.00000001]


array([ 8.        , 15.00000001])

In [17]:
# 4변수함수 미분구하기
# f(w,x,y,z) = wx + xyz + 3w + zy^2, f'(1.0,2.0,3.0,4.0)
def func1(input_obj):
    
    w = input_obj[0,0] #이번엔 행렬로 전달
    x = input_obj[0,1] #이번엔 행렬로 전달
    y = input_obj[1,0] #이번엔 행렬로 전달
    z = input_obj[1,1] #이번엔 행렬로 전달
    
    return (w*x + x*y*z + 3*w + z*np.power(y,2) )

In [19]:
#입력을 2x2행렬로 구성함
input = np.array([ [1.0,2.0], [3.0,4.0] ] )
numerical_derivative(func1, input)
#디버그문 while문 돌아가는걸 보면
#입력변수 w값 > x변수 > y변수 > z변수 순으로 편미분이 계산되고 grad에 저장되는걸 볼수있다

debug 1. inital input variable = [[1. 2.]
 [3. 4.]]
debug 2. inital grad = [[0. 0.]
 [0. 0.]]
debug 3. idx = (0, 0) , x[idx]=  1.0
debug 4. grad[idx] 5.000000000023874
debug 5. grad =  [[5. 0.]
 [0. 0.]]
debug 3. idx = (0, 1) , x[idx]=  2.0
debug 4. grad[idx] 13.00000000000523
debug 5. grad =  [[ 5. 13.]
 [ 0.  0.]]
debug 3. idx = (1, 0) , x[idx]=  3.0
debug 4. grad[idx] 32.00000000006753
debug 5. grad =  [[ 5. 13.]
 [32.  0.]]
debug 3. idx = (1, 1) , x[idx]=  4.0
debug 4. grad[idx] 15.000000000000568
debug 5. grad =  [[ 5. 13.]
 [32. 15.]]


array([[ 5., 13.],
       [32., 15.]])