#### numpy 라이브러리 마지막 (3)

#### concatenate

In [8]:
import numpy as np
#행렬에 새로운 행, 열 추가하기
A = np.array([[10,20,30], [40,50,60]]) #행마다 적어놓은거임
print(A.shape)
#A행렬에 추가할 행렬, 1행 3열로 reshape
#벡터는 행렬구분 없으므로 reshape하는거
row_add = np.array([70,80,90]).reshape(1,3) 

#A행렬에 추가할 행렬, 2행 1열로 생성
#가로가 아니라 세로로 길쭉한 거임 1000이 위
column_add = np.array([1000, 2000]).reshape(2, 1)

#numpy.concatenate 에서 axis = 0행(row)기준
#A행렬에 row_add 행렬 추가
B = np.concatenate((A, row_add), axis = 0)
print(B)
#numpy.concatenate 에서 axis = 1 열(row)기준
#A행렬에 column_add 행렬 추가
C = np.concatenate((A, column_add), axis = 1)
print(C)
#요약, 넣을 행렬을 reshape하고 axis = 0 or 1 해서 넣자

(2, 3)
[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[  10   20   30 1000]
 [  40   50   60 2000]]


#### numpy.loadtxt

In [10]:
loaded_data = np.loadtxt('./data-01.csv', delimiter=',', dtype = np.float32) #25*4인 행렬데이터로부터
x_data = loaded_data[:, 0:-1] #x는 모든 행 데이터와 1열에서 3열까지 (0열은 없다 1부터시작) 데이터를 가져옴
t_data = loaded_data[:, 0:-1] #t는 모든 행 데이터와 -1 즉 마지막 4열의 데이터만 가져옴

#데이터 차원 및 shape 확인
print("x_data.ndim = ", x_data.ndim, ", x_data.shape = ", x_data.shape)
print("t_data.ndim = ", t_data.ndim, ", t_data.shape = ", t_data.shape)

OSError: ./data-01.csv not found.