### numpy (2)

#### 행렬 곱(dot product)

In [1]:
#앞벡터의 열벡터와 뒷벡터의 행벡터가 같아야함
#같지 않다면 reshape나 transpose를 해서 맞춰줄것
import numpy as np
A = np.array([ [1,2,3], [4,5,6] ]) #2*3 행렬 (가로로길쭉)
B = np.array([ [-1,-2], [-3, -4], [-5,-6] ]) # 3*2행렬

#(2x3) dot product (3x2) == (2x2) 행렬
C = np.dot(A,B) #행렬 곱 수행

#matrix A, B 형상 출력 => shape
print("A.shape==", A.shape,"B.shape==", B.shape,"C.shape==", C.shape)
print(C)

A.shape== (2, 3) B.shape== (3, 2) C.shape== (2, 2)
[[-22 -28]
 [-49 -64]]


In [2]:
#행렬의 사칙연산은 입력행렬과 A*B를 다 맞춰줘야 하나 행렬곱은 원하는크기 행렬을 만들수있음
#특성값행렬이 매우커도 열과 행벡터만 맞춰주면 됨

#### numpy broadcast

In [3]:
#크기가 다른 두행렬간에도 사칙연산을 할수있도록 확장해주는기능
#차원이 작은쪽이 큰쪽의 행단위로 반복적으로크기맞추고 계산
A = np.array([ [1,2], [3,4] ])
b = 5

print(A+b) #b를 ([ [5,5], [5,5] ])로 맞춰줌


[[6 7]
 [8 9]]


In [4]:
C = np.array([ [1,2], [3,4] ])
D = np.array([4,5])
print(C+D) #np.array([4,5], [4,5])로 맞춰줌
#단, 이건 행렬곱에는 적용안됨

[[5 7]
 [7 9]]


#### 전치행렬(transpose)

In [5]:
#1행(가로)는 1열로 2행은 2열로 바뀐 행렬
A = np.array([ [1,2], [3,4], [5,6] ]) #3x2행렬
B = A.T
print(A.shape, B.shape)
print(A)
print(B)

(3, 2) (2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [6]:
#vector 전치행렬
#벡터는 열과 행을 구별하지 않음
C = np.array([1,2,3,4,5])
D = C.T
E = C.reshape(1,5) #1*5행렬로 reshape
F = E.T
print(C.shape)
print(D.shape) #벡터라서 전치안됨
print(E.shape)
print(F.shape) #이렇게해야적용됨
print(F)

(5,)
(5,)
(1, 5)
(5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]


#### 행렬 인덱싱, 슬라이싱

In [7]:
#리스트처럼 인덱싱, 슬라이싱 가능
A = np.array([10,20,30,40,50,60]).reshape(3,2)
print(A.shape)
print(A)

(3, 2)
[[10 20]
 [30 40]
 [50 60]]


In [8]:
print(A[0,0]) #행,열
print(A[0],[0]) #행 열 (같은뜻이다)
print(A[2,1])
print(A[2],[1])

10
[10 20] [0]
60
[50 60] [1]


In [9]:
#인덱스 0인 1행부터 인덱스 -1-1=2인 2행까지의 모든 데이터
# , 뒤에는 열임 2열부터 2-1=1인 2열까지의 모든데이터
# 1:4이면 1+1:4-1이므로 2번째부터 3번째까지인샘 
print("A[0:-1, 1:2] ==", A[0:-1, 1:2])

A[0:-1, 1:2] == [[20]
 [40]]


In [10]:
print("A[:,0]==",A[:,0]) #모든행 열하나 (길쭉한 10 30 50임)
print("A[:,:]==",A[:,:]) #모든열

A[:,0]== [10 30 50]
A[:,:]== [[10 20]
 [30 40]
 [50 60]]


#### numpy행렬 iterator

In [11]:
#행렬의 모든원소를 첨부터 끈까지 access하는 경우 사용
#next()메서드를 통해 데이터값을 첨부터 끝까지 순차적으로 읽음
import numpy as np
A = np.array([ [10,20,30,40], [50, 60, 70, 80] ])
print(A,"\n")
print("A.shape ==", A.shape, "\n")
#행렬A의 iterator생성
it = np.nditer(A, flags =['multi_index'], op_flags=['readwrite'])
while not it.finished:
    idx = it.multi_index
    print("current value => ", A[idx])
    it.iternext()
#2x4행렬의 경우 (0,0)=>(0,1)..순서로 access 가져올수 있음
                                        

[[10 20 30 40]
 [50 60 70 80]] 

A.shape == (2, 4) 

current value =>  10
current value =>  20
current value =>  30
current value =>  40
current value =>  50
current value =>  60
current value =>  70
current value =>  80
